### ISSUE TITLE
Error with mysqlite3

### ISSUE THREAD

**Issue by jasondyoungberg** [timburr1/yelpForAnything#4]
Before starting, I ran `npm i`, it install several packages, and when I ran `node app` it gave me the following error:
```
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\jyoun8228\OneDrive - West Ada School District\Documents\!coding\yelp\server\node_modules\sqlite3\lib\binding\napi-v3-win32-x64\node_sqlite3.node'
Require stack:
- C:\Users\jyoun8228\OneDrive - West Ada School District\Documents\!coding\yelp\server\node_modules\sqlite3\lib\sqlite3-binding.js
- C:\Users\jyoun8228\OneDrive - West Ada School District\Documents\!coding\yelp\server\node_modules\sqlite3\lib\sqlite3.js  
- C:\Users\jyoun8228\OneDrive - West Ada School District\Documents\!coding\yelp\server\sqliteDao.js
- C:\Users\jyoun8228\OneDrive - West Ada School District\Documents\!coding\yelp\server\app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\jyoun8228\OneDrive - West Ada School District\Documents\!coding\yelp\server\node_modules\sqlite3\lib\sqlite3-binding.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\jyoun8228\\OneDrive - West Ada School District\\Documents\\!coding\\yelp\\server\\node_modules\\sqlite3\\lib\\sqlite3-binding.js',
    'C:\\Users\\jyoun8228\\OneDrive - West Ada School District\\Documents\\!coding\\yelp\\server\\node_modules\\sqlite3\\lib\\sqlite3.js',
    'C:\\Users\\jyoun8228\\OneDrive - West Ada School District\\Documents\\!coding\\yelp\\server\\sqliteDao.js',
    'C:\\Users\\jyoun8228\\OneDrive - West Ada School District\\Documents\\!coding\\yelp\\server\\app.js'
  ]
}
```

**Comment by timburr1** [comment]
Not sure exactly what's going on there, have you tried deleting your node_modules folder and rebuilding the project?

**Comment by jasondyoungberg** [comment]
I tried this with a fresh download, no modifications

**Comment by timburr1** [comment]
Seems like an issue with the laptop security policy, but Jason was able to get it working: https://github.com/jasondyoungberg/yelpForAnything 

I will work on getting Node.js and MySql added to the company portal before Q3, so hopefully we won't have to deal with this again.
